POST http://localhost:5500/api/send-otp HTTP/1.1
Content-Type: application/json

{
    "phone" : "7289008054"
}

### 
POST http://localhost:5500/api/verify-otp HTTP/1.1
Content-Type: application/json

{
    "phone" : "7289008054",
    "otp": "2494",
    "hash":"3ebc120133ead57165c3884b91a5c70fa56d4a8028f1061f5aef7433a9973fe8.1699333355667"
}

###
GET http://localhost:5500/api/refresh HTTP/1.1
Content-Type: application/json

